### PR TITLE
use universal dbus org.freedesktop.login1 to logout of sessions

### PR DESCRIPTION
**Pull request by soumyaDghosh**
Just one problem I found is everytime I import a backup the fonts of the app gets a little smaller. Can't figure out why.

### CODE REVIEW

**Comment by vikdevelop** [comment]
In the Snap sandbox, there's a missing the wget package that's needed for downloading the file-settings.json file for synchronization and libnotify-bin for sending notifications. Because of this, SaveDesktop cannot download the desired file and start synchronizing and sending notifications.

Output from terminal for sync:
```bash
$ savedesktop --sync
sh: 1: wget: not found
Traceback (most recent call last):
  File "/snap/savedesktop/x1/usr/network_sharing.py", line 220, in <module>
    Syncing()
  File "/snap/savedesktop/x1/usr/network_sharing.py", line 58, in __init__
    self.get_file_info()
  File "/snap/savedesktop/x1/usr/network_sharing.py", line 67, in get_file_info
    with open("file-settings.json") as j:
FileNotFoundError: [Errno 2] No such file or directory: 'file-settings.json'
```

**Comment by soumyaDghosh** [comment]
Okay.. tested, this. Looks good, so, kindly review it.

**Comment by vikdevelop** [comment]
> image
> 
> image
> 
> This is what I am talking about. Look how small and inappropriate the fonts look.
> 
> Also, do you have any idea on this error? I mean from where they may come? I am not able to find one.
> 
> ```
> sh: 0: sh: 0: getcwd() failed: No such file or directory
> getcwd() failed: No such file or directory
> ```

Closing the window and logging out of the system via the application deletes the cache, so in the case of the snap it also deletes the `fontconfig` folder.

**Comment by soumyaDghosh** [comment]
> Closing the window and logging out of the system via the application deletes the cache, so in the case of the snap it also deletes the `fontconfig` folder.

`fontconfig` file spearate for the snap. So, it should not be able to do so. But I'll look into this lead. You can probably merge this PR for now.

**Comment by soumyaDghosh** [comment]
You will need to add `--talk-name=org.freedesktop.login1` in the flatpak manifest and remove all the other talk names

**Pull request merged**
